### ISSUE TITLE
Rotated objects in Tiled appear in the wrong location

### ISSUE THREAD

**Issue by bunny-therapist** [pythonarcade/arcade#1805]
## System Info
Arcade 3.0.0.dev20
------------------
vendor: Intel
renderer: Intel(R) UHD Graphics
version: (3, 3)
python: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
platform: win32
pyglet version: 2.0.6
PIL version: 9.4.0

Tiled 1.9.2

### Actual behavior:

An object which in Tiled is rotated by 90 degrees appears at a position (-1,+1) relative to where it is placed in Tiled. An object roated by -90 degrees appears at (+1,-1).

### Expected behavior:

A rotated tile appears in an arcade game in the same position as it does in Tiled.

### Steps to reproduce/example code:

Create a map in Tiled. Place an object at a position. Rotate it by 90 degrees by editing its properties in Tiled. Load it using `arcade.load_tilemap` and view the results. Compare the position of the object with where it appears in Tiled.

(I am aware this might possibly be a bug in pytiled-parser rather than arcade, but it is hard for me to determine, so I will create an issue here. If we are sure this is in pytiled-parser, I can create an issue there instead if needed.)

**Comment by pushfoo** [comment]
> An object which in Tiled is rotated by 90 degrees appears at a position (-1,+1) relative to where it is placed in Tiled. An object roated by -90 degrees appears at (+1,-1).

This may be due to rotation changes in 3.0.0. If you have time, could you please add vanicat's fork as a remote and clone #1741 to see if it fixes the problem?

I haven't worked with tiled much and I'm not sure if I have it installed at the moment, so I'm not the best person to investigate this.

Possibly related / dupes:

* #1740
* #1763

**Comment by Cleptomania** [comment]
I believe this is fixed in dev22. See https://github.com/pythonarcade/arcade/issues/1695

Let me know if it’s not the same as that issue, but it sounds like the same thing to me. I’m unfortunately relatively unavailable to work on much of anything for at least the next probably 3 months, so not sure when I would be able to get to fixing this.

**Comment by bunny-therapist** [comment]
I will try dev22 if it is released.

Btw, this is very similar to something I previously reported: https://github.com/pythonarcade/arcade/issues/928
I think arcade would benefit from some kind of tests to guard against regressions. For example, have a small Tiled map with rotated objects that gets loaded in a test and then the position of the objects gets asserted.

**Comment by Cleptomania** [comment]
Actually this may be another side effect of the rotation direction switch, I can’t remember what way Tiled goes. You can try negating the value on this line and see if that helps: https://github.com/pythonarcade/arcade/blob/1a17591c54083a0cc16e6f351f1828157b26acb9/arcade/tilemap/tilemap.py#L865

The issue I linked was related to the flip/rotate tools on Tiles, but I think what you’re reporting is the actual rotation values on object layers correct?

In terms of tests we would certainly welcome some more. Pytiled-parser has a ton of test maps/tilesets that could be hijacked for building unit tests.

**Comment by bunny-therapist** [comment]
Afaik, the rotation of the object itself is fine (I did not double check), the issue is the position. Editing the rotation property in Tiled causes the object to appear in a different position in an arcade game than in Tiled.

Actually, when you change the rotation in Tiled, the position of the object changes, but then one usually moves it to where it is wanted.

The issue is that the position of objects in Tiled does not match their positionin arcade.

(I see dev22 is not released? I can maybe test some branch/fork later.)

**Comment by bunny-therapist** [comment]
I installed `arcade @ git+https://github.com/pythonarcade/arcade@b4428e8` (development branch, https://github.com/pythonarcade/arcade/commit/b4428e816fa9fe061717e8f0e803e67ff5bd9289) and the problem is still there.

**Comment by einarf** [comment]
Do we have any simple test case for this? You can do things in lots of different ways in tiled. It can take quite a bit of time just reproducing it.

**Comment by bunny-therapist** [comment]
Do I need to clarify the "Steps to reproduce"? It is hard to write a simple test case for it, as you would need to actually have a file created in Tiled. I suppose I could try to make a test with an added Tiled file using arcade's default resources.

**Comment by bunny-therapist** [comment]
How about this: https://github.com/bunny-therapist/arcade_issue_1805

When I open map.tmx in Tiled 1.9.2, the two aliens are not touching each other. When I run main.py to load and view the map in arcade, they are overlapping. I included screenshots in the repo.

(You need to install requirements.txt in "venv" in that same directory so that the filepath in the tmx file is correct.)

**Comment by bunny-therapist** [comment]
Actually, looking at this now, it seems like it is not just the position that is changed; the alien is also rotated the wrong angle. (Head is facing in a different direction in arcade than in tiled.)

I suppose that that is a result of arcade deciding to have angles increase in the clockwise direction whereas Tiled considers rotations to be be counterclockwise (which makes sense; I have never seen anyone define angles like new arcade does). So, that would mean I would either have to stop rotating objects in Tiled completely, or work around it by rotating them the other way in my head and accept everything looks wrong when editing levels...

**Comment by vanicat** [comment]
Hello,
Could you test my recent pull request (#1831), it could be a fix both your problem.

**Comment by bunny-therapist** [comment]
I tested it and verified that it does in fact fix everything.

**Comment by bunny-therapist** [comment]
Any updates on this?
