### ISSUE TITLE
Animated sprite in tiled map doesn't have correct hit box

### ISSUE THREAD

**Issue by jonsole** [pythonarcade/arcade#1918]
## System Info

Arcade 3.0.0.dev25
------------------
vendor: NVIDIA Corporation
renderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
version: (3, 3)
python: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
platform: win32
pyglet version: 2.0.9
PIL version: 10.0.1

### Actual behavior:

An animated tile or object in tiled map has a hitbox which covers the whole set of textures
![image](https://github.com/pythonarcade/arcade/assets/15461752/e25dd77d-354d-488b-83b3-baa2600ccb84)
![image](https://github.com/pythonarcade/arcade/assets/15461752/fa8e10a2-6205-490e-8f35-1b3e83f9233d)

### Expected behavior:

The hitbox should cover the current frame only (or all frames when placed on top of each other)
![image](https://github.com/pythonarcade/arcade/assets/15461752/8e1fa110-e722-4049-9aa7-3b04cfca8d36)

**Comment by jonsole** [comment]
The causes seems to be Sprite.texture only creates a hitbox the first time (when self._texture is get_default_texture())

![image](https://github.com/pythonarcade/arcade/assets/15461752/d1989f21-f166-4cd0-9b7f-cb8b70d71c50)

Removing the check resolves the issue but presumably there's a reason for the check in the first place?

**Comment by Cleptomania** [comment]
Sorry for the late response on this, do you happen to have an example repo or something with this problem? I've not seen this happen before(and in fact, the hitbox should be updating to reflect the current frame).

If you're on Arcade 2.6 this may be related to a previous issue with Animated Sprites loaded from spritesheet animations, 2.6 has a bug with that and Animated sprites only really work if each frame is it's own image file. That behavior is fixed for 3.0 though.

**Comment by jonsole** [comment]
Hi, I've uploaded the example to https://github.com/jonsole/arcade-example
I've been using 3.0.0-dev.26 as I did find the issue with animated sprites in 2.6,

**Comment by einarf** [comment]
> Removing the check resolves the issue but presumably there's a reason for the check in the first place?

I suspect there's a missing `not`. There's also some incompatibilitiess in the animated sprite classes due to a new restriction in 3.0. Sprites cannot be created without a texture. These classes needs some minor changes to clean this up.

Should be able to resolve this properly very soon.

**Comment by einarf** [comment]
Definitely still a problem in latest dev branch
![bilde](https://github.com/pythonarcade/arcade/assets/5418180/01a4214e-0bd6-4727-bef0-ae0396fb33a2)

**Comment by einarf** [comment]
The initial texture was passed into the sprite initializer. Dropping this argument only allowing to supply textures based on keygrames fixes this issue.

![bilde](https://github.com/pythonarcade/arcade/assets/5418180/b7a01d4b-5d7a-4a52-9fff-ad8f2de64ed7)

**Comment by einarf** [comment]
Fixed in 2e0bc4bf7e80cc48b971931024bf57457ec415f8

Also ran your project and it seems to work fine
